package com.example.woof.ui.theme

import androidx.compose.ui.graphics.Color

// Tema claro
val md_theme_light_primary = Color(0xFF4A90E2) // Azul brillante para el color primario
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD0E7FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D4F)
val md_theme_light_secondary = Color(0xFF6A4A99) // Morado para el color secundario
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE6D7FF)
val md_theme_light_onSecondaryContainer = Color(0xFF2E1A4A)
val md_theme_light_tertiary = Color(0xFF3F51B5) // Azul medio para el terciario
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCDD8FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001A5A)
val md_theme_light_error = Color(0xFFD32F2F)
val md_theme_light_errorContainer = Color(0xFFFFCDD2)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF790000)
val md_theme_light_background = Color(0xFFF0F4FF)
val md_theme_light_onBackground = Color(0xFF1C1F2E)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1C1F2E)
val md_theme_light_surfaceVariant = Color(0xFFE1E4F0)
val md_theme_light_onSurfaceVariant = Color(0xFF3A3D4A)
val md_theme_light_outline = Color(0xFF757986)
val md_theme_light_inverseOnSurface = Color(0xFFF5F6FA)
val md_theme_light_inverseSurface = Color(0xFF2D2F39)
val md_theme_light_inversePrimary = Color(0xFFB0CFFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF4A90E2)
val md_theme_light_outlineVariant = Color(0xFFC1C6D4)
val md_theme_light_scrim = Color(0xFF000000)

// Tema oscuro
val md_theme_dark_primary = Color(0xFFB0CFFF)
val md_theme_dark_onPrimary = Color(0xFF002A67)
val md_theme_dark_primaryContainer = Color(0xFF00408F)
val md_theme_dark_onPrimaryContainer = Color(0xFFD0E7FF)
val md_theme_dark_secondary = Color(0xFFD1B4FF)
val md_theme_dark_onSecondary = Color(0xFF3A215A)
val md_theme_dark_secondaryContainer = Color(0xFF4D3784)
val md_theme_dark_onSecondaryContainer = Color(0xFFE6D7FF)
val md_theme_dark_tertiary = Color(0xFFADB8FF)
val md_theme_dark_onTertiary = Color(0xFF19206D)
val md_theme_dark_tertiaryContainer = Color(0xFF3446B5)
val md_theme_dark_onTertiaryContainer = Color(0xFFCDD8FF)
val md_theme_dark_error = Color(0xFFFFA4A2)
val md_theme_dark_errorContainer = Color(0xFF8B0000)
val md_theme_dark_onError = Color(0xFF680000)
val md_theme_dark_onErrorContainer = Color(0xFFFFCDD2)
val md_theme_dark_background = Color(0xFF1C1F2E)
val md_theme_dark_onBackground = Color(0xFFE6E7EF)
val md_theme_dark_surface = Color(0xFF1C1F2E)
val md_theme_dark_onSurface = Color(0xFFE6E7EF)
val md_theme_dark_surfaceVariant = Color(0xFF3A3D4A)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C6D4)
val md_theme_dark_outline = Color(0xFF8B8D9C)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1F2E)
val md_theme_dark_inverseSurface = Color(0xFFE6E7EF)
val md_theme_dark_inversePrimary = Color(0xFF4A90E2)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB0CFFF)
val md_theme_dark_outlineVariant = Color(0xFF3A3D4A)
val md_theme_dark_scrim = Color(0xFF000000)
